### ISSUE TITLE
link with cookiecutter?

### ISSUE THREAD

**Issue by SylvainTakerkart** [INT-NIT/AnDO#41]
Hi @Slowblitz 

I just came back to the cookiecutter concept (which I'd discovered a few years ago, but then forgot): https://cookiecutter.readthedocs.io/

I'm wondering whether:
- AnDO could become a cookiecutter template? or whether it's totally redundant?
- we could get inspiration from the cookiecutter command line interface to setup the base of an AnDO toplevel directory (as you'd started doing a while ago)
- we could think about providing a cookiecutter template for a neuroscience research project (and inside this, there would be a data directory that should follow AnDO or BIDS for example)

Anyhow, this might a good thing to think about during the new confinement ;) This is maybe to be taken a bit more widely than only at the AnDO/data level, which you might be interested in... (???)

**Comment by Slowblitz** [comment]
Hello,
So why not using cookiecutter I have already done a little template a while ago?  
On the tool to create a new AnDO directory that I have created, it may be a little redundant if we are planing to use cookiecutter no ?
And ,Yes it seems a good idea to make cookiecutter template for a neuroscience research project( BIDS or AnDO) but I think I am  not enough aware on what is mandatory or option in naming for example in BIDS to make good templates at the moment.

Maybe we should schedule a meeting to talks about it ?

**Comment by Slowblitz** [comment]
Hello ,
here's my coockiecutter template for AnDO if you want to check it out =) 
https://github.com/Slowblitz/Cookiecutter_Neuro_Templates

**Comment by SylvainTakerkart** [comment]
cool, I'll check it out this afternoon!

**Comment by SylvainTakerkart** [comment]
ok, I've tested, it's nice and easy to create a directory with the AnDO structure ready to go! great!!! ;)

I see 3 points to discuss:
- most importantly, is this redondant with the AnDO specs? we cannot have both systems in place because we do not want to maintain them both separately... if there is an added value to this cookiecutter (a question that still needs to be answered), we should find a way to make them co-exist so that if the specs evolve, we only need to change them in one place! for example: would it be possible that the cookiecutter.json file is the same as (or is automatically generated by) the json file from the AnDO specs? (or the opposite... maybe we could modify the json file from the AnDO specs so that it is the same as the cookiecutter.json, since I guess this one needs to respect some format?)
- we should talk to some users to see what they need to automatize this process of creation... (how do they want to provide the input information? a list of subjects, a list of sessions, in what format? etc.)
- once we know all this, maybe we can implement something for this automation...

let's talk! and maybe let's talk with kevin!

**Comment by Slowblitz** [comment]
Hello, if it works that cool  ;),
For the first question, the specs of AnDO and the one for cookiecutter are really different both uses a specific syntax and I don't think we can reverse the REGEX of AnDO specs to create a directory, I have to think about it to see if we can make the two works together.

And yes we should talk to  the users maybe they don't need to automatize the creation. Moreover, the creation is very specific and happens once in a project no ? Maybe something that "adds" subject to an existing project is more suited I don't really know ? WDYT ?

Ok let's talk about it ! =)

**Comment by SylvainTakerkart** [comment]
@BlaizeKevin we might want to discuss with you soon ;)

**Comment by blaizeke** [comment]
Great ! :) Let me know when you will be ready !

**Comment by BlaizeKevin** [comment]
Great ! Let me know when you will be ready ! :)

**Comment by Slowblitz** [comment]
Hi @BlaizeKevin  are you up for a meeting this week to talk about it ?

**Comment by SylvainTakerkart** [comment]
only tomorrow thursday works for me...

**Comment by BlaizeKevin** [comment]
Tomorrow (Thursday) morning at 11AM ?

**Comment by SylvainTakerkart** [comment]
ok for 11am! let's stop using this github issue to set up our meeting, I'll send you an email ;)

**Comment by SylvainTakerkart** [comment]
@Slowblitz for info: https://neurostars.org/t/bids-and-cookiecutter/17367

**Comment by SylvainTakerkart** [comment]
Interim conclusion was: cookiecutter is probably too limited / too simple compared to what we need...
