### ISSUE TITLE
change repo name and module API

### ISSUE THREAD

**Issue by SylvainTakerkart** [INT-NIT/AnDO#48]
Hi, as discussed here (https://github.com/INT-NIT/AnDOCreator/issues/1), we need to

1. rename this repo to AnDO

2. rethink the structure of the code, to make the three tools (Checker, Generator, Viewer) exist at the same level of hierarchy... also, before doing this fairly vast refactoring of the code, let's discuss and decide on which API we want to settle... how do we want to import these tools? 
- `from AnDO import Generator` (and the same with the two other tools)
- or are there other options? @JuliaSprenger @Slowblitz 

3. let us discuss the name `Checker` vs `Validator`... indeed, as @JuliaSprenger mentioned in the other discussion, `Validator` might be better, but we had just chosen `Checker` to distinguish this from what exists in BIDS... WDYT?

**Comment by JuliaSprenger** [comment]
Yes, I agree with the suggestions for renaming this repo to AnDO. However, I don't have the rights to do this so one of you has to use your power. I can take care of renaming the modules.

**Comment by SylvainTakerkart** [comment]
ok, I just changed the name of the repo...
