### ISSUE TITLE
Should `customSesField` be mandatory?

### ISSUE THREAD

**Issue by JuliaSprenger** [INT-NIT/AnDO#50]
In the current implementatino `customSesField` can be empty resulting in folder names like this:
`ses-20000101_001_`. Having a folder name ending on `_` is for once not appealing and might lead to confusion on the user side.

I would argue that we either omit the trailing underscore if no `customSesField` is provided or enforce `customSesField` to not be empty. The latter however leads to artificially long folder names in cases when this might actually not be required, therefore introducing more complexity (and potentially confusion) on the user side. We should also keep in mind, that if we follow the BIDS style in the future our choice here might also be propagated to the naming of the data files, therefore it is even more important to have a clean and simple solution at this point.

What do you think?

**Comment by SylvainTakerkart** [comment]
> I think we should make it optional and include this in the next version of the ando specifications.

ok! so let's keep the related problems / bugs "undealt with" for now... and we'll discuss what to do precisely for the AnDO specs v2!

we should probably create a github project for the AnDO v2 ;)

**Comment by SylvainTakerkart** [comment]
@JuliaSprenger  project created: https://github.com/INT-NIT/AnDO/projects/2
I let you add stuff to it!

**Comment by JuliaSprenger** [comment]
This is an issue for the RedCap Diglab and is not part of AnDO (anymore)
