### ISSUE TITLE
Add unittests to travis

### ISSUE THREAD

**Issue by JuliaSprenger** [INT-NIT/AnDO#51]
I think currently the unittests are not run by travis. We need to update the travis configuration to include these again.

**Comment by SylvainTakerkart** [comment]
Hi, seeing the recent change in travis billing (see e.g https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works), are we sure we still want to use travis?

See for example for what's envisioned in nilearn, which points to what has been done in mne: https://github.com/nilearn/nilearn/issues/2627

**Comment by JuliaSprenger** [comment]
That is good to know. CircleCIs free plan (single job only) might also be an alternative to github actions as we could run the tests on linux and window with it.

**Comment by JuliaSprenger** [comment]
For now tests are running on travis again (#53). Let's keep it like this for now until we encounter further issues with travis.
