### ISSUE TITLE
merging functions in engine.py

### ISSUE THREAD

**Issue by SylvainTakerkart** [INT-NIT/AnDO#60]
Hi!

Looking at the code, I realize that we have several functions that do the same thing at different levels of the hierarchy, or for different files...

is_experiment_folder
is_subject_folder
is_session_folder
is_ephys_folder

and

is_Data_file
is_DataSetDescription_file
is_SubjectDescription_file

I think it would be nice to merge each of these two groups into a single function (that would result in two functions: one for the files, one for the directories) by adding an input argument to specify at which level / on which file the function gets applied...

**Comment by JuliaSprenger** [comment]
So here we are just talking about the existence of folders and files, and not the check of the content, right? This will definitely require dedicated functions.
I think the separation here between folders and files comes from the concept, that general regex rules can be used to check if a path is AnDO compatible. If both currently versions only do this then we should merge them. For checking of the existence of required files we need an extra function then.
So in principle we need to cover these levels:
- check if existing paths are AnDO compatible (folders & files)
- check if all required files are present, also taking into account dependencies between files
- check the content of the existing files for required entries

**Comment by SylvainTakerkart** [comment]
yep, I'm not discussing what these functions do! this was just a very simple comment (or a "note for later") on the existing code: the four functions (is_experiment_folder, is_subject_folder, is_session_folder, is_ephys_folder) are strictly identical except for the hardcoded path that points to the corresponding rule (experiment, subject, session, ephys) in the function... so clearly these should be one function with an additional argument...

**Comment by SylvainTakerkart** [comment]
ok, this has been fixed in https://github.com/INT-NIT/AnDO/pull/63
