### ISSUE TITLE
Validator error

### ISSUE THREAD

**Issue by Slowblitz** [INT-NIT/AnDO#79]
So it seems that if one of the data file eg : 'nwb' or 'nix' are missing in the data set , no error were raised by the validator.
See also https://github.com/INT-NIT/AnDO/pull/73

**Comment by JuliaSprenger** [comment]
this should be fixed also in #80, @Slowblitz. so can we close this one?

**Comment by Slowblitz** [comment]
Yes #80 is now fixed also
